FROM registry.access.redhat.com/ubi10-beta/ubi:10.0-beta-1741674993

ENV ASAHI_VISIBLE_DEVICES 1
COPY . /src/ramalama
WORKDIR /src/ramalama
RUN container-images/scripts/build_llama_and_whisper.sh asahi
WORKDIR /
