FROM registry.access.redhat.com/ubi10-beta/ubi:10.0-beta-1741674993

COPY . /src/ramalama
WORKDIR /src/ramalama
RUN container-images/scripts/build-cli.sh /usr/bin
WORKDIR /

ENTRYPOINT [ "ramalama" ]
